name: pipeline

# interesting
on:
  push:
    branches: [master]
    
jobs:
  test-suite:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python v3.8
        uses: action/setup-python@v2

        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: unittest
        run: |
          python -m unittest discover src/tests/